apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "crud.fullname" . }}-configmap
data:
  application.yml: |
    server:
      port: ${APP_PORT}
      shutdown: graceful
    spring:
      datasource:
        url: ${POSTGRES_URL}
        username: ${POSTGRES_APP_USER}
        password: ${POSTGRES_APP_PASSWORD}
        driver-class-name: org.postgresql.Driver
      jpa:
        hibernate:
          ddl-auto: update
