apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crud.fullname" . }}-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ include "crud.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "crud.fullname" . }}
    spec:
      containers: 
        - name: crud-app
          image: aboldyrev1111/otushomework:v4
          #env
          env:
          - name: POSTGRES_APP_USER
            valueFrom:
              secretKeyRef:
                name: {{ include "crud.fullname" . }}-secrets
                key: appUsername
          - name: POSTGRES_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "crud.fullname" . }}-secrets
                key: appPassword
          - name: POSTGRES_URL
            valueFrom:
              secretKeyRef:
                name: {{ include "crud.fullname" . }}-secrets
                key: appDbUrl
          - name: APP_PORT
            value: "{{.Values.service.port}}"
          #volumeMounts
          volumeMounts:
          - name: crud-configmap
            mountPath: /opt/otus-homework/config
          #livenessProbe
          livenessProbe:
            httpGet:
              path: /health
              port: web
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
          #readinessProbe
          readinessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 15
            periodSeconds: 2 
          #ports
          ports:
          - name: web
            containerPort: {{.Values.service.port}}              
            protocol: TCP
      volumes:
        - name: crud-configmap
          configMap:
            name: {{ include "crud.fullname" . }}-configmap                  