apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}-secrets
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  username: {{.Values.postgresql.adminUser|b64enc}}        #b3R1c2FkbWlu #otusadmin
  password: {{.Values.postgresql.adminPassword|b64enc}}   #b3R1c2FkbWlu #otusadmin
  appUsername: {{.Values.postgresql.appUser|b64enc}}      #b3R1c3VzZXI= #otususer
  appPassword: {{.Values.postgresql.appPassword|b64enc}}  #b3R1c3VzZXI= #otususer
  appDatabase: {{.Values.postgresql.appDatabase|b64enc}}  #b3R1c2Ri #otusdb
      